---

- name: delete deployment config
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ responder_service_application_name }}"
    namespace: "{{ namespace }}"
    kind: dc

- name: delete service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ responder_service_application_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: delete route
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ responder_service_application_name }}"
    namespace: "{{ namespace }}"
    kind: route

- name: delete buildconfig
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ responder_service_buildconfig_name }}"
    namespace: "{{ namespace }}"
    kind: buildconfig

- name: delete imagestream
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ responder_service_application_name }}"
    namespace: "{{ namespace }}"
    kind: imagestream

- name: delete configmap
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ responder_service_application_name }}"
    namespace: "{{ namespace }}"
    kind: configmap

- name: delete service account
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ service_account }}"
    namespace: "{{ namespace }}"
    kind: serviceaccount

- name: delete rolebinding
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ service_account }}-view"
    namespace: "{{ namespace }}"
    kind: rolebinding

