---

application_monitoring_namespace: emergency-response-monitoring
application_monitoring_release: '0.0.5-monitoring-key'
application_monitoring_resources_repo: https://raw.githubusercontent.com/aidenkeating/application-monitoring-operator/{{ application_monitoring_release }}/deploy
application_monitoring_label_value: emergency-response

monitoring_sa: "{{ application_monitoring_resources_repo }}/operator_roles/service_account.yaml"
monitoring_role: "{{ application_monitoring_resources_repo }}/operator_roles/role.yaml"
monitoring_role_binding: "{{ application_monitoring_resources_repo }}/operator_roles/role_binding.yaml"
monitoring_operator: "{{ application_monitoring_resources_repo }}/operator.yaml"

monitoring_cr: application_monitoring_cr.yml
monitoring_prom_crb: prometheus_cluster_role_binding.yml
monitoring_am_crb: alert_manager_cluster_role_binding.yml
monitoring_graf_crb: grafana_cluster_role_binding.yml
monitoring_prom_operator_crb: prometheus_operator_cluster_role_binding.yml
