apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: emergency-response-prometheus-application-monitoring-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-application-monitoring-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: "{{ application_monitoring_namespace }}"
userNames:
- system:serviceaccount:{{ application_monitoring_namespace }}:prometheus-operator
