---

application_name: "{{ responder_service_application_name }}"

service_account: responder-service

application_configmap: responder-service
logging_configmap: responder-service-logging

application_properties: application.properties

git_url: https://github.com/NAPS-emergency-response-project/responder-service.git
git_ref: master

application_image: redhat-openjdk18-openshift:1.4
application_image_namespace: openshift

buildconfig_name: "{{ application_name }}-binary"
buildconfig_template: responder-service-binary-buildconfig.yml

imagestream_name: "{{ application_name }}"
imagestream_template: responder-service-imagestream.yml

application_template: responder-service.yml

logging_style: dev