apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    build: {{ pipeline_buildconfig_name }}
  name: {{ pipeline_buildconfig_name }}
  annotations:
spec:
  runPolicy: Serial
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        def git_repo = "{{ incident_service_git_repo }}"
        def git_branch = "{{ incident_service_git_branch }}"
        def namespace_jenkins = "{{ namespace_tools }}"
        def namespace_app = "{{ namespace }}"
        def app_build = "{{ buildconfig_name }}"
        def app_imagestream = "{{ imagestream_name }}"
        def app_name = "{{ application_name }}"

        node ('nodejs') {
          stage ('S2I Build') {
            openshift.withCluster() { // Use "default" cluster or fallback to OpenShift cluster detection
              def bc = openshift.selector("bc", "${app_build}")
              def builds = bc.startBuild()
              timeout (15) {
                builds.watch {
                  if ( it.count() == 0 ) {
                    return false
                  }
                  // Print out the build's name and terminate the watch
                  echo "Detected new builds created by buildconfig: ${it.names()}"
                  return true
                }
                builds.untilEach(1) {
                  return it.object().status.phase == "Complete"
                }
              }
            }
          }

          stage ('Deploy') {
            openshift.withCluster() {
              openshift.withProject( "${namespace_app}") {
                openshift.tag("${namespace_jenkins}/${app_imagestream}:latest", "${namespace_app}/${app_imagestream}:latest")
                def dc_app = openshift.selector("dc", "${app_name}")
                timeout (5) {
                  dc_app.untilEach(1) {
                    return it.object().status.readyReplicas == 1
                  }
                }
              }
            }
          }
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: {{ github_secret }}
    type: GitHub
  - generic:
      secret: {{ generic_secret }}
    type: Generic
