---

home_dir: "{{ playbook_dir }}/.."

# resources dir
resources_base_dir: "{{ home_dir }}/resources"

# oc executable
openshift_cli: oc

project_name: naps-emergency-response

monitoring_label: prometheus
