---

application_name: "{{ emergency_console_application_name }}"

service_account: emergency-console

resources_limits_cpu: 500m
resources_limits_memory: 300Mi
resources_requests_cpu: 200m
resources_requests_memory: 100Mi

application_image: nodejs:10
application_image_namespace: openshift

buildconfig_name: "{{ application_name }}"
buildconfig_template: emergency-console-buildconfig.yml

pipeline_buildconfig_name: "{{ application_name }}-pipeline"
pipeline_buildconfig_template: emergency-console-pipeline.yml

imagestream_name: "{{ application_name }}"
imagestream_template: emergency-console-imagestream.yml

application_template: emergency-console.yml

git_url: "{{ emergency_console_git_repo }}"
git_ref: master

emergency_console_config_configmap: emergency-console-config
rhsso_config_configmap: "{{ sso_config_configmap }}"

emergency_console_config_map_token: "{{ map_token | default('') }}"
emergency_console_config_polling: 10000
